apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-label
  template:
    metadata:
      labels:
        app: redis-label
    spec:
      containers:
        - name: redis
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
          image: 008770191051.dkr.ecr.us-east-2.amazonaws.com/redis:6.2.6-debian-10-r120
          env:
          - name: "ALLOW_EMPTY_PASSWORD"
            value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis-label
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: redis