apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: flags-api-pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: flags-api-label
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flags-api-deployment
  labels:
    app.kubernetes.io/name: flags-api-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flags-api-label
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: flags-api-label
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - flags-api-label
              topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - flags-api-label
                topologyKey: topology.kubernetes.io/zone
      containers:
        - name: flags-api
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
          image: 008770191051.dkr.ecr.us-east-2.amazonaws.com/flags-e2e:latest
          command: ['node']
          args: ['dist/server/index.js']
          env:
            - name: REDIS_SERVICE_SERVICE_HOST
              value: "e2e-flags.gzkp6i.ng.0001.use2.cache.amazonaws.com"
            - name: "HOST"
              value: "0.0.0.0"
            - name: "PORT"
              value: "3000"
          ports:
          - containerPort: 3000
            protocol: TCP
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-fetcher-job
  labels:
    app.kubernetes.io/name: cron-fetcher-label
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cron-fetcher
              imagePullPolicy: Always
              resources:
                requests:
                  memory: "1Gi"
                  cpu: "1"
                limits:
                  memory: "1Gi"
                  cpu: "1"
              image: 008770191051.dkr.ecr.us-east-2.amazonaws.com/flags-e2e:latest
              command: ['node']
              args: ['dist/cron/index.js']
              env:
                - name: REDIS_SERVICE_SERVICE_HOST
                  value: "e2e-flags.gzkp6i.ng.0001.use2.cache.amazonaws.com"
                - name: AWS_REGION
                  value: "us-east-2"
                - name: CRON_INTERVAL
                  value: "5"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: flags-api-internal.optibus.com
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  name: flags-api-service
  namespace: e2e-flags
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: flags-api-label
  sessionAffinity: None
  type: LoadBalancer