apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: e2e-flags-secret-optibus-integrations
spec:
  refreshInterval: 1h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store # name of the ClusterSecretStore (or kind specified)
  target:
    name: e2e-flags-secret-optibus-integrations # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: AFTERMATH_SECRET
      remoteRef:
        key: aftermath-armada-api-token
