apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: e2e-flags-airtable-secret
spec:
  refreshInterval: 1h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store # name of the ClusterSecretStore (or kind specified)
  target:
    name: e2e-flags-airtable-secret  # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: airtable-flags-api-key