apiVersion: v1
kind: ConfigMap
metadata:
  name: e2e-flags-config
data:
  HOST:  "0.0.0.0"
  PORT: "3000"
  
  REDIS_SERVICE_SERVICE_HOST: "e2e-flags.gzkp6i.ng.0001.use2.cache.amazonaws.com"

  AWS_REGION: {{ .Values.aws.region }}

  AFTERMATH_FEATURES_URL: {{ .Values.aftermath.features_url }}