apiVersion: apps/v1
kind: Deployment
metadata:
  name: flags-api-deployment
  labels:
    app.kubernetes.io/name: flags-api-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flags-api-label
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: flags-api-label
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - flags-api-label
              topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - flags-api-label
                topologyKey: topology.kubernetes.io/zone
      containers:
        - name: flags-api
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
          image: {{ .Values.ecr.image }}
          command: ['node']
          args: ['dist/services/server/index.js']
          envFrom:
            - configMapRef:
                name: e2e-flags-config
            - secretRef:
                name: e2e-flags-secret-optibus-integrations
          ports:
          - containerPort: 3000
            protocol: TCP
      tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: on-schedule-2023
      nodeSelector:
        node.kubernetes.io/instancegroup: on-schedule-2023