apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: flags-api-external.optibus.com
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-04dbcc737d45362ad
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:008770191051:certificate/d3f1d4be-312d-4c49-a025-35a7fefdd47b
    service.beta.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=optibus-access-logs-us-east-2,access_logs.s3.prefix=e2e-flags
  name: flags-api-service-external
  namespace: e2e-flags
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  loadBalancerClass: service.k8s.aws/nlb
  ports:
  - name: http
    nodePort: 31860
    port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    app: flags-api-label
  sessionAffinity: None
  type: LoadBalancer