apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flags-api-ingress
  namespace: e2e-flags
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.alb.certificate_arn }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=optibus-access-logs-us-east-2,access_logs.s3.prefix=e2e-flags
spec:
  ingressClassName: alb
  rules:
    - host: flags-api-internal2.optibus.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flags-api-service
                port:
                  number: 443
