apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: e2e-flags
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-label
  sessionAffinity: None
  type: ClusterIP